-- psql -d FEC -f schema/schema.sql

DROP DATABASE IF EXISTS FEC;
CREATE DATABASE FEC;

DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS chars;
DROP TABLE IF EXISTS chars_review_join;


CREATE TABLE reviews (
  review_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  product_id INT NOT NULL,
  rating smallint NOT NULL,
  date varchar(50) NOT NULL,
  summary varchar(255) NOT NULL,
  body varchar(1000) NOT NULL,
  recommend boolean NOT NULL,
  reported boolean NOT NULL DEFAULT false,
  reviewer_name varchar(50) NOT NULL,
  reviewer_email varchar(50) NOT NULL,
  response varchar(255) DEFAULT NULL,
  helpfulness INT NOT NULL DEFAULT 0
);


CREATE TABLE photos (
  photos_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  url varchar(255) DEFAULT NULL,
  review_id INT NOT NULL
);


CREATE TABLE chars (
  id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id INT NOT NULL,
  chars_name varchar(50) NOT NULL,
  count INT NOT NULL DEFAULT 0,
  total INT NOT NULL DEFAULT 0
);

CREATE TABLE chars_review_join (
  id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  chars_id INT NOT NULL,
  review_id INT NOT NULL,
  value SMALLINT NOT NULL
);



